stages:
  centralized_train:
    cmd: python src/initializer.py --train_type centralized --dataset_size 4000 --samples_path
      data/gtex/v8_samples.parquet --dataset_size 4000 --expressions_path data/gtex/v8_expressions.parquet
      --metrics_path data/metrics --n_epochs 2
    deps:
    - data/gtex/v8_expressions.parquet
    - data/gtex/v8_samples.parquet
    - src/initializer.py
    metrics:
    - data/metrics/centralized_metrics.json:
        cache: false
  decentralized_train:
    cmd: python src/initializer.py --train_type decentralized --dataset_size 4000
      --samples_path data/gtex/v8_samples.parquet --dataset_size 4000 --expressions_path
      data/gtex/v8_expressions.parquet --metrics_path data/metrics --n_epochs 2 --no_of_clients
      4
    deps:
    - data/gtex/v8_expressions.parquet
    - data/gtex/v8_samples.parquet
    - src/initializer.py
    metrics:
    - data/metrics/decentralized_metrics.json:
        cache: false
