name: pysyft_v029
channels:
  - conda
  - defaults
  - conda-forge
dependencies:
  - pip=20.2.2
  - python=3.7
  - ipython=7.15.0
  - nb_conda_kernels
  - scikit-learn=0.22.2
  - dvc=1.6.1
  - click=7.1.2
  - numpy=1.18.5
  - pandas=1.0.3
  - keras==2.4.3
  - jupyterlab>=2.2.4
  - pyyaml==5.3.1
  - requests==2.23.0
  - pyarrow==1.0.1
  - pip:
    - syft==0.2.8
