name: pysyft_v029
channels:
  - conda
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip>=20.2.2
  - nb_conda_kernels
  - scikit-learn>=0.22.2
  - dvc>=1.6.6
  - click=7.1.2
  - numpy=1.18.5
  - pandas=1.1.1
  - keras==2.4.3
  - jupyterlab>=2.2.4
  - pyyaml==5.3.1
  - requests==2.23.0
  - pyarrow==1.0.1
  - progressbar2>= 3.52.1
  - matplotlib>=3.3.1
  - papermill>=2.1.2
  - pip:
    - syft==0.2.8
