name: pysyft_v028
channels:
  - conda
dependencies:
  - pip=20.2.2
  - python=3.6.10
  - ipython=7.15.0
  - nb_conda_kernels
  - pip:
    - syft==0.2.8
    - click==7.1.2
    - ipykernel==5.3.4
    - keras==2.4.3
    - notebook==5.7.8
    - numpy==1.18.5
    - pandas==1.0.3
    - pyyaml==5.3.1
    - requests==2.22.0
    - scikit-learn==0.22.2
    - pyarrow==0.17.1