name: pysyft_v028
channels:
  - conda
  - defaults
  - conda-forge
dependencies:
  - pip=20.2.2
  - python=3.7.9
  - ipython=7.15.0
  - nb_conda_kernels
  - scikit-learn=0.22.2
  - dvc=1.6.6
  - click=7.1.2
  - numpy=1.18.5
  - pandas=1.1.1
  - pyyaml=5.3.1
  - requests=2.23.0
  - pyarrow=0.17.1
  - jupyterlab=2.2.4
  - keras=2.3.1
  - ipykernel=5.3.4
  - progressbar2=3.52.1
  - matplotlib=3.3.1
  - papermill=2.1.2
  - pip:
    - syft==0.2.8

