name: openmined
channels:
  - conda
dependencies:
  - python=3.7.6
  - ipykernel=5.3.0
  - ipython=7.15.0
  - pip=20.1.1
  - nb_conda_kernels
  - pip:
    - -r openmined-requirements.txt
    - notebook
    - tornado==6.0.4
