name: pysyft
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.2.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - decorator=4.4.2
  - entrypoints=0.3
  - ipykernel=5.3.0
  - ipython=7.15.0
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - libcxx=10.0.0
  - libffi=3.2.1
  - libsodium=1.0.17
  - ncurses=6.1
  - openssl=1.1.1g
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pyzmq=19.0.1
  - readline=8.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.30.1
  - tk=8.6.10
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - aioice==0.6.18
    - aiortc==0.9.28
    - astor==0.8.1
    - av==8.0.2
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - crc32c==2.0
    - cryptography==2.9.2
    - flask==1.1.2
    - flask-socketio==4.2.1
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - h5py==2.10.0
    - idna==2.8
    - importlib-metadata==1.6.1
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lz4==3.0.2
    - markdown==3.2.2
    - markupsafe==1.1.1
    - msgpack==1.0.0
    - netifaces==0.10.9
    - numpy==1.18.5
    - opt-einsum==3.2.1
    - phe==1.4.0
    - pillow==6.2.2
    - protobuf==3.12.2
    - psutil==5.7.0
    - pycparser==2.20
    - pyee==7.0.2
    - pylibsrtp==0.6.6
    - python-engineio==3.13.0
    - python-socketio==4.6.0
    - pyyaml==5.3.1
    - requests==2.22.0
    - scipy==1.4.1
    - syft==0.2.6
    - syft-proto==0.4.8
    - tblib==1.6.0
    - tensorboard==1.15.0
    - tensorflow==1.15.3
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - tf-encrypted==0.5.7
    - torch==1.4.0
    - torchvision==0.5.0
    - tornado==4.5.3
    - urllib3==1.25.9
    - websocket-client==0.57.0
    - websockets==8.1
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0

